"""initial db

Revision ID: 5e02e4d81a0b
Revises: 9f4d4cbd2cf8
Create Date: 2024-06-02 01:02:46.858886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e02e4d81a0b'
down_revision: Union[str, None] = '9f4d4cbd2cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
